apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tor-hidden-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tor-hidden-service
    spec:
      containers:
        - name: tor-hidden-service
          image: tor:least
          env:
            - name: TOR_SERVICE_KEY
              value: ""
            - name: TOR_HOSTNAME
              value: ""
          ports:
            - containerPort: 80
